from __future__ import annotations

from dataclasses import asdict
from typing import Iterable
from uuid import uuid4

from packages.schemas.domain import AgentRole, Task, TaskStatus
from services.persistence.repository import Repository

from .ruata import RuataOrchestrator, TaskSpec


class OrchestrationService:
    def __init__(self, repository: Repository) -> None:
        self.repository = repository
        self.planner = RuataOrchestrator()

    def plan_task(self, task: Task) -> list[Task]:
        spec = TaskSpec(
            task_id=task.task_id,
            project_id=task.project_id,
            title=task.title,
            description=task.description,
            risk_level=task.risk_level,
            acceptance_criteria=task.acceptance_criteria,
            allowed_paths=task.allowed_paths,
            metadata=task.metadata,
        )
        plan = self.planner.plan(spec)
        children: list[Task] = []
        for planned in plan:
            child = Task(
                task_id=f"{planned.id}-{uuid4().hex[:4]}",
                project_id=task.project_id,
                title=f"{planned.action.replace('_', ' ').title()} — {task.title}",
                description=(
                    f"Specialist task generated by Ruata for parent {task.task_id}. "
                    f"Action: {planned.action}."
                ),
                risk_level=planned.risk_level,
                assigned_agent=planned.agent,
                status=TaskStatus.BACKLOG,
                dependencies=planned.depends_on,
                allowed_paths=task.allowed_paths,
                acceptance_criteria=planned.acceptance_criteria,
                metadata={"parent_task_id": task.task_id, "planner": "ruata", "plan": asdict(planned)},
            )
            self.repository.create_task(child)
            children.append(child)
        return children
