create table if not exists public.profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.projects (project_id text primary key, owner_id uuid references auth.users(id) on delete set null, name text not null, repository_url text, default_branch text not null default 'main', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workspace_members (workspace_id text not null, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member', created_at timestamptz not null default now(), primary key (workspace_id, user_id));
create table if not exists public.devices (device_id text primary key, owner_id uuid references auth.users(id) on delete set null, name text not null, platform text not null, hostname text not null, status text not null default 'offline', vs_code_version text, bridge_version text, last_seen timestamptz, created_at timestamptz not null default now());
create table if not exists public.workspaces (workspace_id text primary key, project_id text not null references public.projects(project_id) on delete cascade, device_id text not null references public.devices(device_id) on delete cascade, name text not null, path text not null, registered boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(device_id,path));
alter table public.workspace_members add constraint workspace_members_workspace_fk foreign key (workspace_id) references public.workspaces(workspace_id) on delete cascade;
create table if not exists public.agents (agent_id text primary key, name text not null, role text not null unique, version text not null default '0.1.0', enabled boolean not null default true, configuration jsonb not null default '{}'::jsonb);
create table if not exists public.agent_versions (agent_id text not null references public.agents(agent_id) on delete cascade, version text not null, configuration jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), primary key(agent_id,version));
create table if not exists public.tasks (task_id text primary key, project_id text not null references public.projects(project_id) on delete cascade, title text not null, description text not null, risk_level text not null default 'low', assigned_agent text references public.agents(agent_id), status text not null default 'backlog', dependencies text[] not null default '{}', allowed_paths text[] not null default '{}', acceptance_criteria text[] not null default '{}', metadata jsonb not null default '{}'::jsonb, version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.task_dependencies (task_id text not null references public.tasks(task_id) on delete cascade, depends_on_task_id text not null references public.tasks(task_id) on delete restrict, primary key(task_id,depends_on_task_id), check(task_id <> depends_on_task_id));
create table if not exists public.task_runs (run_id text primary key, task_id text not null references public.tasks(task_id) on delete cascade, agent text not null, status text not null default 'queued', attempt integer not null default 1, started_at timestamptz, finished_at timestamptz, error text, output_artifact_ids text[] not null default '{}');
create table if not exists public.executions (execution_id text primary key, run_id text not null references public.task_runs(run_id) on delete cascade, tool_name text not null, input jsonb not null default '{}'::jsonb, status text not null default 'queued', exit_code integer, stdout text not null default '', stderr text not null default '', duration_ms integer);
create table if not exists public.tool_requests (tool_request_id text primary key, task_id text references public.tasks(task_id) on delete cascade, run_id text references public.task_runs(run_id) on delete cascade, agent text not null, tool_name text not null, input jsonb not null default '{}'::jsonb, risk_level text not null default 'low', policy_decision text, approval_id text, status text not null default 'requested', created_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.artifacts (artifact_id text primary key, task_id text not null references public.tasks(task_id) on delete cascade, kind text not null, name text not null, uri text, content_type text, sha256 text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.approvals (approval_id text primary key, task_id text not null references public.tasks(task_id) on delete cascade, action text not null, risk_level text not null, status text not null default 'pending', requested_by uuid references auth.users(id) on delete set null, decided_by uuid references auth.users(id) on delete set null, reason text, created_at timestamptz not null default now(), decided_at timestamptz);
create table if not exists public.audit_events (event_id text primary key, event_type text not null, actor text not null, user_id uuid references auth.users(id) on delete set null, task_id text references public.tasks(task_id) on delete set null, device_id text references public.devices(device_id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.task_state_history (history_id text primary key, task_id text not null references public.tasks(task_id) on delete cascade, from_status text, to_status text not null, version integer not null, actor text, reason text, created_at timestamptz not null default now());
create table if not exists public.idempotency_keys (key text not null, scope text not null, response jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), primary key(key,scope));
create table if not exists public.model_usage (usage_id text primary key, user_id uuid references auth.users(id) on delete set null, task_id text references public.tasks(task_id) on delete set null, agent text, model text, input_tokens integer, output_tokens integer, total_tokens integer, estimated_cost numeric(18,8), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.evaluations (evaluation_id text primary key, task_id text references public.tasks(task_id) on delete set null, suite text not null, status text not null, score numeric(10,4), details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists idx_projects_owner on public.projects(owner_id);
create index if not exists idx_workspaces_project on public.workspaces(project_id);
create index if not exists idx_workspaces_device on public.workspaces(device_id);
create index if not exists idx_workspace_members_user on public.workspace_members(user_id);
create index if not exists idx_tasks_project_status on public.tasks(project_id,status);
create index if not exists idx_tasks_updated_at on public.tasks(updated_at desc);
create index if not exists idx_runs_task on public.task_runs(task_id,attempt desc);
create index if not exists idx_audit_task_created on public.audit_events(task_id,created_at desc);
create index if not exists idx_task_history_task_created on public.task_state_history(task_id,created_at desc);
create index if not exists idx_approvals_task_status on public.approvals(task_id,status,created_at desc);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(user_id) values (new.id) on conflict (user_id) do nothing; return new; end; $$;
revoke all on function public.handle_new_user() from public;
create or replace trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_workspace_member(target_workspace text) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.workspace_members wm where wm.workspace_id = target_workspace and wm.user_id = auth.uid()); $$;
revoke all on function public.is_workspace_member(text) from public;
grant execute on function public.is_workspace_member(text) to authenticated;
create or replace function public.is_project_member(target_project text) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.projects p where p.project_id = target_project and p.owner_id = auth.uid()) or exists(select 1 from public.workspace_members wm join public.workspaces w on w.workspace_id=wm.workspace_id where w.project_id=target_project and wm.user_id=auth.uid()); $$;
revoke all on function public.is_project_member(text) from public;
grant execute on function public.is_project_member(text) to authenticated;
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.workspace_members enable row level security;
alter table public.devices enable row level security;
alter table public.workspaces enable row level security;
alter table public.agents enable row level security;
alter table public.agent_versions enable row level security;
alter table public.tasks enable row level security;
alter table public.task_dependencies enable row level security;
alter table public.task_runs enable row level security;
alter table public.executions enable row level security;
alter table public.tool_requests enable row level security;
alter table public.artifacts enable row level security;
alter table public.approvals enable row level security;
alter table public.audit_events enable row level security;
alter table public.task_state_history enable row level security;
alter table public.idempotency_keys enable row level security;
alter table public.model_usage enable row level security;
alter table public.evaluations enable row level security;
create policy profiles_self_select on public.profiles for select to authenticated using(user_id=auth.uid());
create policy profiles_self_update on public.profiles for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy projects_member_select on public.projects for select to authenticated using(public.is_project_member(project_id));
create policy projects_owner_insert on public.projects for insert to authenticated with check(owner_id=auth.uid());
create policy projects_owner_update on public.projects for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy workspace_members_self_select on public.workspace_members for select to authenticated using(user_id=auth.uid() or public.is_workspace_member(workspace_id));
create policy devices_owner_select on public.devices for select to authenticated using(owner_id=auth.uid() or exists(select 1 from public.workspaces w where w.device_id=device_id and public.is_project_member(w.project_id)));
create policy devices_owner_insert on public.devices for insert to authenticated with check(owner_id=auth.uid());
create policy devices_owner_update on public.devices for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy workspaces_member_select on public.workspaces for select to authenticated using(public.is_project_member(project_id));
create policy agents_authenticated_select on public.agents for select to authenticated using(true);
create policy agent_versions_authenticated_select on public.agent_versions for select to authenticated using(true);
create policy tasks_member_select on public.tasks for select to authenticated using(public.is_project_member(project_id));
create policy task_dependencies_member_select on public.task_dependencies for select to authenticated using(public.is_project_member((select project_id from public.tasks t where t.task_id=task_dependencies.task_id)));
create policy task_runs_member_select on public.task_runs for select to authenticated using(public.is_project_member((select project_id from public.tasks t where t.task_id=task_runs.task_id)));
create policy executions_member_select on public.executions for select to authenticated using(public.is_project_member((select project_id from public.tasks t join public.task_runs r on r.task_id=t.task_id where r.run_id=executions.run_id)));
create policy tool_requests_member_select on public.tool_requests for select to authenticated using(public.is_project_member((select project_id from public.tasks t where t.task_id=tool_requests.task_id)));
create policy artifacts_member_select on public.artifacts for select to authenticated using(public.is_project_member((select project_id from public.tasks t where t.task_id=artifacts.task_id)));
create policy approvals_member_select on public.approvals for select to authenticated using(public.is_project_member((select project_id from public.tasks t where t.task_id=approvals.task_id)));
create policy audit_member_select on public.audit_events for select to authenticated using(task_id is not null and public.is_project_member((select project_id from public.tasks t where t.task_id=audit_events.task_id)));
create policy history_member_select on public.task_state_history for select to authenticated using(public.is_project_member((select project_id from public.tasks t where t.task_id=task_state_history.task_id)));
create policy evaluations_member_select on public.evaluations for select to authenticated using(task_id is not null and public.is_project_member((select project_id from public.tasks t where t.task_id=evaluations.task_id)));
create policy model_usage_member_select on public.model_usage for select to authenticated using(user_id=auth.uid() or (task_id is not null and public.is_project_member((select project_id from public.tasks t where t.task_id=model_usage.task_id))));
alter publication supabase_realtime add table public.tasks;
alter publication supabase_realtime add table public.task_runs;
alter publication supabase_realtime add table public.approvals;
alter publication supabase_realtime add table public.devices;
alter publication supabase_realtime add table public.workspaces;
