create schema if not exists private;
drop policy if exists devices_owner_select on public.devices;
drop policy if exists workspaces_member_select on public.workspaces;
drop policy if exists projects_member_select on public.projects;
drop policy if exists workspace_members_self_select on public.workspace_members;
drop policy if exists tasks_member_select on public.tasks;
drop policy if exists task_dependencies_member_select on public.task_dependencies;
drop policy if exists task_runs_member_select on public.task_runs;
drop policy if exists executions_member_select on public.executions;
drop policy if exists tool_requests_member_select on public.tool_requests;
drop policy if exists artifacts_member_select on public.artifacts;
drop policy if exists approvals_member_select on public.approvals;
drop policy if exists audit_member_select on public.audit_events;
drop policy if exists history_member_select on public.task_state_history;
drop policy if exists evaluations_member_select on public.evaluations;
drop policy if exists model_usage_member_select on public.model_usage;
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop function if exists public.is_workspace_member(text);
drop function if exists public.is_project_member(text);
create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(user_id) values (new.id) on conflict (user_id) do nothing; return new; end; $$;
create or replace function private.is_workspace_member(target_workspace text) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.workspace_members wm where wm.workspace_id = target_workspace and wm.user_id = auth.uid()); $$;
create or replace function private.is_project_member(target_project text) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.projects p where p.project_id = target_project and p.owner_id = auth.uid()) or exists(select 1 from public.workspace_members wm join public.workspaces w on w.workspace_id=wm.workspace_id where w.project_id=target_project and wm.user_id=auth.uid()); $$;
revoke all on function private.handle_new_user() from public;
revoke all on function private.is_workspace_member(text) from public;
grant execute on function private.is_workspace_member(text) to authenticated;
revoke all on function private.is_project_member(text) from public;
grant execute on function private.is_project_member(text) to authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure private.handle_new_user();
create policy projects_member_select on public.projects for select to authenticated using(private.is_project_member(project_id));
create policy workspace_members_self_select on public.workspace_members for select to authenticated using(user_id=auth.uid() or private.is_workspace_member(workspace_id));
create policy devices_owner_select on public.devices for select to authenticated using(owner_id=auth.uid() or exists(select 1 from public.workspaces w where w.device_id=device_id and private.is_project_member(w.project_id)));
create policy workspaces_member_select on public.workspaces for select to authenticated using(private.is_project_member(project_id));
create policy tasks_member_select on public.tasks for select to authenticated using(private.is_project_member(project_id));
create policy task_dependencies_member_select on public.task_dependencies for select to authenticated using(private.is_project_member((select project_id from public.tasks t where t.task_id=task_dependencies.task_id)));
create policy task_runs_member_select on public.task_runs for select to authenticated using(private.is_project_member((select project_id from public.tasks t where t.task_id=task_runs.task_id)));
create policy executions_member_select on public.executions for select to authenticated using(private.is_project_member((select project_id from public.tasks t join public.task_runs r on r.task_id=t.task_id where r.run_id=executions.run_id)));
create policy tool_requests_member_select on public.tool_requests for select to authenticated using(private.is_project_member((select project_id from public.tasks t where t.task_id=tool_requests.task_id)));
create policy artifacts_member_select on public.artifacts for select to authenticated using(private.is_project_member((select project_id from public.tasks t where t.task_id=artifacts.task_id)));
create policy approvals_member_select on public.approvals for select to authenticated using(private.is_project_member((select project_id from public.tasks t where t.task_id=approvals.task_id)));
create policy audit_member_select on public.audit_events for select to authenticated using(task_id is not null and private.is_project_member((select project_id from public.tasks t where t.task_id=audit_events.task_id)));
create policy history_member_select on public.task_state_history for select to authenticated using(private.is_project_member((select project_id from public.tasks t where t.task_id=task_state_history.task_id)));
create policy evaluations_member_select on public.evaluations for select to authenticated using(task_id is not null and private.is_project_member((select project_id from public.tasks t where t.task_id=evaluations.task_id)));
create policy model_usage_member_select on public.model_usage for select to authenticated using(user_id=auth.uid() or (task_id is not null and private.is_project_member((select project_id from public.tasks t where t.task_id=model_usage.task_id))));
revoke all on table public.idempotency_keys from anon, authenticated;
